### ISSUE TITLE
Replacing _helpers.tpl with our charts.adfinis.com/common library

### ISSUE THREAD

**Issue by sinicis** [adfinis-sygroup/helm-charts#182]
**Is your feature request related to a problem? Please describe.**
No it does not. It would just remove an overhead.

**Describe the solution you'd like**
We could use `charts.adfinis.com/common` instead of rewriting `_helpers.tpl` for every chart. In fact we should also add some `selectorLabels` functionality in the common chart.

**Describe alternatives you've considered**
Leave it as it is

**Affected chart**
It's affecting all existing an future charts.

**Additional context**
The idea comes from @eyenx - I'm just the documenter here.

**Comment by hairmare** [comment]
I like `commons` and I encourage people to use it, it is nevertheless what I would consider advanced helming. Thus I  don't want to mandate it's usage on all new charts since it adds to the already high level of complexity for new Helm chart hackers.

Generally I'd like to see more adoption of the library pattern. In our charts it's usage is fine since most of the `*apps` use `common`  via the `argoconfig` chart. In other generic charts like `csi-secret-provider-class` it's also used. My focus was on these cases since the see a very broad adoption and using `common` in them works across a wide range of deployments. In other cases I usually use `common` since i'm too lazy to copy paste a full on metadata block, it does tend to waste some time if I create nested stuff like in the `cert-manager-issuers` chart.

**Comment by luk43** [comment]
replacing the templates in a chart should be considered for advanced usecases.
the effort seems currently not worth it. please reopen the issue if there are objections.
